version: '3'
services:
  db:
    # container_name: postgres
    image: "postgres:11.1"
    env_file:
      - ./resources/postgres_config/env_file
    networks:
      - db_nw

  pyramid_app:
#    build: .
#    stdin_open: true
#    tty: true
    image: image_from_dockerfile
    env_file:
      - ./resources/postgres_config/env_file
    volumes:
      # - ./volumes/pyramid_app_config:/app/site_config
      - ./volumes/src:/app/src
      - ./volumes/venv:/app/venv
#    - ./logs:/var/log
#    - ./config:/etc/appconfig
    image: image_from_dockerfile
    working_dir: /app
    # expose:
    #   - 6543
#    command: /app/venv/bin/pserve /app/site_config/development.ini --reload
    command: >
      sh -c "mkdir -p /app/venv &&
             python3 -m venv /app/venv &&
             ls /app/venv &&
             /app/venv/bin/pip install --upgrade pip setuptools &&
             /app/venv/bin/pip install -r /app/src/requirements.pip &&
             /app/venv/bin/pip install -e '/app/src[testing]' &&
             /app/venv/bin/pserve /app/src/development.ini --reload"

    ## /volumes/pyramid_app_config/requirements.pip /app/site_config/requirements.pip
    # /app/venv/bin/pip install -r /app/site_config/requirements.pip
    ## /volumes/pyramid_app_config/setup.py /app/setup.py
    # /app/venv/bin/pip install -e "./app[testing]"
    # /app/venv/bin/pserve /app/testsite_config/development.ini --reload

    # command: >
    #   sh -c "virtualenv /app/venv &&
    #          /app/venv/bin/pip install -r /app/testsite_config/requirements.pip &&
    #          /app/venv/bin/pip install -e '.[testing]' &&
    #          /app/venv/bin/pserve /app/testsite_config/development.ini --reload"
    # /app/venv/bin/pserve /app/testsite_config/development.ini --reload
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

  nginx:
    image: nginx:1.13.5
    ports:
      - "6543:80"
    volumes:
      - ./volumes/nginx_config:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - pyramid_app

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  conf.d:
  src:
