version: '3'
services:
  db:
    # container_name: postgres
    image: "postgres:11.1"
    env_file:
      - ./resources/postgres_config/env_file
    networks:
      - db_nw

  pyramid_app:
    stdin_open: true
    tty: true
    image: image_from_dockerfile
    env_file:
      - ./resources/postgres_config/env_file
    volumes:
      - ./volumes/src:/app/src
      - ./volumes/venv:/app/venv
    image: image_from_dockerfile
    working_dir: /app
    command: /app/venv/bin/pserve /app/src/development.ini --reload
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

  nginx:
    image: nginx:1.13.5
    ports:
      - "6543:80"
    volumes:
      - ./volumes/nginx_config:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - pyramid_app

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  conf.d:
  src:
